#include "TgmApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<TgmApp>()
{
  InputParameters params = validParams<MooseApp>();
  return params;
}

TgmApp::TgmApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  TgmApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  TgmApp::associateSyntax(_syntax, _action_factory);
}

TgmApp::~TgmApp()
{
}

// External entry point for dynamic application loading
extern "C" void TgmApp__registerApps() { TgmApp::registerApps(); }
void
TgmApp::registerApps()
{
  registerApp(TgmApp);
}

// External entry point for dynamic object registration
extern "C" void TgmApp__registerObjects(Factory & factory) { TgmApp::registerObjects(factory); }
void
TgmApp::registerObjects(Factory & /*factory*/)
{
}

// External entry point for dynamic syntax association
extern "C" void TgmApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { TgmApp::associateSyntax(syntax, action_factory); }
void
TgmApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
